version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: jobsearch_postgres
    restart: always
    environment:
      POSTGRES_DB: jobsearch
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pg_data:
