spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobsearch
    username: jobuser
    password: jobpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

jwt:
  secret: V7ZbHn5aX9kM2cR3tQp8YwU1eF4gH7jK2lN6oP9rT0s=
  expiration: 86400000
  refresh-expiration: 604800000 #

gcp:
  bucket: jobsearch-cv-bucket-dev
  credentials-path: /Users/aymericmaillot/IdeaProjects/jobSearch/secrets/projet-perso-466112-2cea5677d075.json

n8n:
  webhook:
    url: https://n8n.srv1369661.hstgr.cloud/webhook-test/ae2883d9-ae48-4aa4-9723-88b6cde3193f
    api-key: ${n8nApiKey}

openai:
  api-key: ${OPENAI_API_KEY}
